export default {
  DATA_SCHEMA_VERSION: 4,
  SOURCE_LIST: [
    'https://bit.ly/iptv-aptv',
    'https://iptv.yang-1989.eu.org/m3u/Gather.m3u',
    'https://bit.ly/jsnzkpg',
    'https://bit.ly/itvlist',
    'https://bit.ly/suxuang-v4',
    // 'https://iptv-org.github.io/iptv/index.m3u',
  ],
  /**
   * 仅放置你有权限使用的咪咕体育直播源。
   * 代码会自动将其归入“咪咕体育”分类，并参与测速/去重/路由。
   * 支持两种写法：
   * 1. 字符串 URL：指向一个包含咪咕体育频道的 m3u 地址
   * 2. 对象：直接声明单条频道，适合手工维护足球/篮球/综合体育分组
   *    { name: '咪咕英超', subcategory: '足球', url: 'https://...' }
   */
  MIGU_SOURCE_LIST: [],
  EPG_SOURCES: [
    'https://iptv-org.github.io/epg/guides/cn.xml',
    'https://iptv-org.github.io/epg/guides/hk.xml',
  ],
  FETCH_TIMEOUT_MS: 8000,
  FETCH_RETRIES: 2,
  VALIDATE_TIMEOUT_MS: 5000,
  VALIDATE_CONCURRENCY: 8,
  MAX_FAILURES: 3,
  UNSTABLE_LATENCY_MS: 3000,
  MAX_SOURCES_PER_CHANNEL: 3,
  KV_TTL: {
    playlist: 86400,
    channels: 86400,
    health: 3600,
    epg: 43200,
    embeddings: 604800,
  },
  CRON_BATCH_SIZE: 20,
  /** 流水线资源上限（防止 6+ 大源合并后触发 Worker 1102 CPU 超限） */
  PIPELINE: {
    maxRawEntries: 4000,
    maxChannels: 800,
    validateMaxChannels: 0,
    validateTimeoutMs: 2000,
    fastDedupeThreshold: 500,
    skipEpgOverChannels: 500,
    skipD1SyncOverChannels: 800,
    skipValidation: false,
    /** 快速模式下的轻量测速（控制并发，避免 1102） */
    liteValidate: true,
    liteValidateMaxChannels: 600,
    liteValidateTimeoutMs: 5000,
    liteValidateBatchSize: 15,
    liteValidateEarlyExit: true,
    liteValidateProbePerChannel: 3,
    /** 仅将测速通过的频道写入 M3U */
    playlistOnlyPlayable: true,
    autoBootstrapOnRequest: true,
  },
  DEDUPE_SIMILARITY_THRESHOLD: 0.82,
  AI: {
    mode: 'rule', // rule | embedding | llm
    llmEndpoint: '',
    embeddingDimensions: 32,
  },
  REGION_COLO_MAP: {
    SIN: 'SEA',
    HKG: 'HK',
    TPE: 'TW',
    NRT: 'JP',
    ICN: 'KR',
  },
  AD_PATTERNS: [
    /广告/i,
    /shopping/i,
    /infomercial/i,
    /test\s*pattern/i,
    /请更换源/i,
    /维护中/i,
  ],
  CHANNEL_FILTER: {
    /** 只保留中文地区高价值频道 */
    chineseRegionOnly: true,
    allowLatinBrands: [
      'CCTV',
      'CGTN',
      'TVB',
      'HOY',
      'ViuTV',
      '凤凰',
      '咪咕',
      'CHC',
    ],
    blockedGroups: [
      /台湾「限制」/i,
      /international/i,
      /overseas/i,
      /english/i,
      /foreign/i,
      /usa/i,
      /uk/i,
      /france/i,
      /germany/i,
      /italy/i,
      /spain/i,
      /japan/i,
      /korea/i,
      /india/i,
      /arab/i,
      /music tv/i,
    ],
    blockedCountryHints: [
      /美国|英国|法国|德国|意大利|西班牙|葡萄牙|荷兰|比利时|瑞士|奥地利|瑞典|挪威|丹麦|芬兰/i,
      /俄罗斯|乌克兰|波兰|希腊|土耳其|罗马尼亚|匈牙利|捷克/i,
      /日本|韩国|朝鲜|印度|巴基斯坦|孟加拉|越南|泰国|老挝|柬埔寨|缅甸|马来西亚|新加坡|印尼|菲律宾/i,
      /伊朗|伊拉克|阿富汗|阿联酋|沙特|卡塔尔|以色列|埃及|南非|尼日利亚|索马里/i,
      /加拿大|巴西|阿根廷|智利|秘鲁|墨西哥/i,
    ],
    blockedNames: [
      /\bBBC\b/i,
      /\bCNN\b/i,
      /\bCNBC\b/i,
      /\bBLOOMBERG\b/i,
      /\bFOX\b/i,
      /\bSKY\b/i,
      /\bHBO\b/i,
      /\bDISCOVERY\b/i,
      /\bANIMAL PLANET\b/i,
      /\bNATIONAL GEOGRAPHIC\b/i,
      /\bMTV\b/i,
      /\bESPN\b/i,
      /\bSTAR SPORTS\b/i,
      /\bEUROSPORT\b/i,
      /\bNHK\b/i,
      /\bKBS\b/i,
      /\bSBS\b/i,
      /\bTV5\b/i,
      /\bTVE\b/i,
      /\bRAI\b/i,
      /\bTF1\b/i,
      /\bZDF\b/i,
      /\bARD\b/i,
      /\bAXN\b/i,
      /\bTHAIPBS\b/i,
      /\bNDTV\b/i,
      /\bMBC\b/i,
      /\bARIRANG\b/i,
      /\bKBS\b/i,
      /\bTRT\b/i,
      /\bODISHA\b/i,
      /\bSANSAD\b/i,
      /\bZEE\b/i,
      /\bFUJI\b/i,
      /\bNITTELE\b/i,
      /\bGOLF NETWORK\b/i,
      /专区/i,
    ],
    blockedUrlPatterns: [
      /iptv\.catvod\.com/i,
      /live\.ottiptv\.cc\/huya/i,
      /live\.ottiptv\.cc\/bilibili/i,
      /douyu1\.php/i,
      /douyin\//i,
      /\/yy\//i,
      /live\.nctv\.top/i,
      /czstream\.com/i,
      /goodiptv\.club\/douyu/i,
      /cdn\.jdshipin\.com:8880\/huya\.php/i,
      /jdshipin\.com\/.*(huya|douyu)/i,
      /kwimgs\.com/i,
      /yximgs\.com/i,
      /ffzy-play/i,
      /cfss\.cc\/api\/kg/i,
      /\.mp4(\?|$)/i,
    ],
    lowValueNames: [
      /专场/i,
      /系列/i,
      /点歌台/i,
      /直播间/i,
      /DJ/i,
      /手游/i,
      /单机/i,
      /海选/i,
      /陪看/i,
      /台长/i,
      /Fans/i,
      /音乐秀/i,
      /精选\d+首/i,
      /合集/i,
      /演唱会完整/i,
      /电影轮播/i,
      /NBA\s*\d+/i,
      /原神|斗地主|QQ飞车|我的世界|拳皇|植物大战僵尸/i,
    ],
    allowValuableSpecials: [
      /CCTV/i,
      /CGTN/i,
      /卫视/i,
      /频道/i,
      /电视台/i,
      /新闻综合/i,
      /公共频道/i,
      /凤凰/i,
      /TVB/i,
      /咪咕/i,
      /CHC/i,
    ],
  },
  SAAS: {
    sessionTtlSeconds: 86400 * 7,
    defaultRole: 'user',
    adminApiKeys: [], // 可在 wrangler secret 或环境变量覆盖
  },
  ROUTING: {
    ispBoost: {
      电信: ['judy-gotv', '.cn'],
      联通: ['judy-gotv', '.cn'],
      移动: ['judy-gotv', 'migu'],
      telecom: ['judy-gotv'],
      unicom: ['judy-gotv'],
      mobile: ['judy-gotv'],
    },
    countryBoost: {
      CN: ['judy-gotv', '.cn'],
      HK: ['iptv-org', 'tvb'],
      TW: ['iptv-org'],
    },
  },
  METRICS: {
    retentionDays: 30,
  },
  STREAM: {
    proxyPath: '/api/stream',
    maxFallbackAttempts: 3,
  },
  CATEGORY_RULES: [
    { name: '咪咕体育', patterns: [/咪咕|migu|miguvideo|cmvideo|咪视界/i, /体育|足球|篮球|NBA|CBA|英超|西甲|欧冠|亚冠|中超|网球|斯诺克|F1|赛车|高尔夫|搏击|UFC/i] },
    { name: '央视频道', patterns: [/CCTV|央视|CGTN/i] },
    { name: '港澳台', patterns: [/\bTVB\b|\bATV\b|明珠|凤凰|凤凰卫视|无线|ViuTV|HOY|澳门|台湾|中视|华视|民视|台视|三立|东森|纬来|中天|耀才|RHK|VIU/i] },
    { name: '卫视频道', patterns: [/卫视/i] },
    { name: '地方频道', patterns: [/(北京|上海|天津|重庆|河北|山西|内蒙古|辽宁|吉林|黑龙江|江苏|浙江|安徽|福建|江西|山东|河南|湖北|湖南|广东|广西|海南|四川|贵州|云南|西藏|陕西|甘肃|青海|宁夏|新疆|深圳|广州|珠海|佛山|东莞|汕头|南宁|海口|南京|苏州|无锡|常州|南通|杭州|宁波|温州|嘉兴|绍兴|金华|合肥|芜湖|福州|厦门|泉州|南昌|赣州|济南|青岛|烟台|郑州|洛阳|武汉|宜昌|长沙|株洲|广州|深圳|珠海|南宁|桂林|海口|三亚|成都|绵阳|贵阳|昆明|拉萨|西安|宝鸡|兰州|西宁|银川|乌鲁木齐|哈尔滨|长春|沈阳|大连)/i, /台|频道|新闻|综合|公共|都市|生活|影视|文体|科教|少儿|教育|法治|民生|农村|城市|导视|家庭|移动电视|体育|休闲/i] },
    { name: '体育', patterns: [/体育|足球|篮球|NBA|CBA|英超|西甲|欧冠|亚冠|中超|ESPN|Sport|F1|网球|斯诺克|高尔夫|搏击|UFC/i] },
    { name: '影视', patterns: [/电影|影院|CHC|影视|电视剧|剧场|影视频道|欢笑剧场|经典剧场/i] },
    { name: '新闻', patterns: [/新闻|资讯|凤凰资讯|新闻频道|新闻综合/i] },
    { name: '少儿动漫', patterns: [/少儿|儿童|卡通|动漫|Cartoon|KAKU|CCTV14|金鹰卡通|动画/i] },
    { name: '纪实人文', patterns: [/纪实|人文|地理|探索|Discovery|National Geographic|求索|风云地理/i] },
    { name: '综艺娱乐', patterns: [/综艺|娱乐|音乐|演唱会|芒果|Show|MTV/i] },
  ],
};
